### PR TITLE
Rails back end

### PR DESCRIPTION
**Pull request by brhanuhailu**
# In this back-end branch I;
- [ ] Create a new Rails API app called 'hello-rails-back-end'.
- [ ] Initialize the project with Git.
- [ ] Made sure that the project has a Postgres database set up.
- [ ] Create a table for storing your messages and create 5 different greetings.
- [ ] Create an API endpoint that selects a random greeting from the table

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @brhanuhailu, please update your backend readme, make it professional and descriptive 👍🏿

**Comment by prolajumokeoni** [comment]
HI @brhanuhailu, please fix the Rubocop linter error 👍🏿

**Comment by brhanuhailu** [comment]
@prolajumokeoni  Thank you very much I am fixing it

**Comment by brhanuhailu** [comment]
Dear @prolajumokeoni I have fixed the linters. Thank you very much for the your time

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Brhanu,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Backen API correctly connects with Reat frontend externally!
🎲 Random greeting are generating correctly!
🎲 ReadMe looks great!

Implementing the above change(s) will make your ReadMe stand out even better! 😉

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
